# Generated by Django 5.0.6 on 2024-05-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='average_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='score_count',
            field=models.IntegerField(default=0),
        ),
    ]
